Admin Panel Route Guard
SELab-2/UGent-7 pull request #350
Opened 2024-04-19 08:43 UTC by bsilkyn

A route guard for the admin panel would be quite handy to prevent non-admins from reaching it in the first place

2024-04-19 08:46 UTC, bsilkyn commented
Wait with merging until demo is done

2024-04-19 18:45 UTC, bsilkyn commented
It can be merged now, after being reviewed

2024-04-19 18:48 UTC, tyboro2002 requested changes

2024-04-19 18:48 UTC, tyboro2002 commented on frontend/src/router/router.ts
> +import { AdminGuard } from '@/router/guards/admin.guard.ts';
from where is this file this is not in the repo

2024-04-19 18:57 UTC, tyboro2002 commented
> It can be merged now, after being reviewed

you can also set the pr to a normal pr instead of a draft to notify this.

2024-04-20 09:10 UTC, francisvaut approved these changes
This is better.

2024-04-20 09:10 UTC, merged