Run checks
SELab-2/UGent-7 pull request #397
Opened 2024-05-02 16:17 UTC by Topvennie

Run extra checks.
Brings some extra changes with it

### Route changes

- Removed POST /api/projects
  - Is made by making a POST request to /api/courses/\<id>/projects
- Moved PUT & PATCH /api/courses/\<id>/projects to /api/projects/\<id>
- Moved PUT & PATCH /api/projects/\<id>/structure-checks to /api/structure-checks/\<id>

### Models

- Structure checks
  - Renamed name to path
- Docker Image
  - Added a state
    - Queued
    - Building
    - Ready
    - Error
- Extra check
  - Added name field
  - Changed timeout to time_limit and changed the meaning
    - Time_limit means the maximum time a docker container runs.
    - Default is 30 seconds so that most of the time infinite loops gets shut down quickly.
    - Should not be used in the script to see if an algorithm is fast enough as the timeout will also stop the bash script.
    - Teachers / assistants still have the possibility to raise the timeout to maximum of 1000 seconds if they know it will take longer than 30 seconds.
  - Added field memory_limit
    - Follows the same reasoning as time_limit
    - Default is 128 MB
    - Max is 1 GB
    - Again, should not be used to limit the maximum amount of memory that a container can use.
- Check Result
  - Removed the following error messages
    - Output limit
    - Internal Error

2024-05-02 18:36 UTC, DeLany123 commented on backend/api/serializers/project_serializer.py
> +        # TODO: ?
?

2024-05-03 08:49 UTC, Topvennie commented on backend/api/serializers/project_serializer.py
> +        # TODO: ?
Will be removed in a future commit.

2024-05-03 13:19 UTC, DeLany123 commented on backend/api/views/project_view.py
> +        print(request.data, flush=True)
!

2024-05-03 14:21 UTC, DeLany123 requested changes
Because of the change to the structureCheckModel, the fixtures do not work anymore (and seeder probably too). It would be nice if these worked first so the frontend developers do not experience errors.

2024-05-03 15:20 UTC, DeLany123 commented
Could it be possible to make a working example? 
By this I mean making it possible to to add a submission where there are working extra checks on the background. This should include a working docker-image, working dockerfile (check from the teacher) and a working submissionfile which we can use to test a submission. In 5f176ab I've tried to make this work myself where you can find the files that I tried making under backend/api/fixtures/data.

2024-05-06 13:37 UTC, DeLany123 commented
Changes requested here!

2024-05-06 13:50 UTC, Topvennie commented
> Changes requested here!

:+1:

2024-05-06 18:45 UTC, DeLany123 commented
Very good very nice!

2024-05-06 18:48 UTC, DeLany123 approved these changes

2024-05-06 18:50 UTC, merged