Login/logout tests
SELab-2/UGent-7 pull request #408
Opened 2024-05-09 17:21 UTC by bsilkyn

These are some e2e tests regarding the login and logout routine

2024-05-11 13:11 UTC, Topvennie requested changes

2024-05-11 13:11 UTC, Topvennie commented on backend/authentication/views.py
> +}
I'd prefer to see this in `ypovoli.settings.py`.
Keep all the configuration together.

2024-05-11 13:11 UTC, Topvennie commented on frontend/src/test/e2e/login.cy.ts
> +    // })
Can this be removed or is it something you want to look at a later date?

2024-05-13 10:35 UTC, DeLany123 commented on frontend/src/router/guards/authentication.guard.ts
> +    console.log(to.name as string);
Can you delete this please.

2024-05-13 10:36 UTC, bsilkyn commented on frontend/src/router/guards/authentication.guard.ts
> +    console.log(to.name as string);
well spotted

2024-05-13 10:43 UTC, merged